version: "3.3"
services:
  spring-sql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecpassword90
      - MYSQL_USER=hbstudent
      - MYSQL_PASSWORD=hbstudent
      - MYSQL_DATABASE=hb_student_tracker
    volumes:
      - my-spring-boot-vol-sql:/var/lib/mysql
  spring-container:
    image: spring-demo
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - spring-sql

  my_phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8088:80"
volumes:
  my-spring-boot-vol-sql:

networks:
  spring-network: